# Site settings
title: innolocity.org/tedn.life
email: roland@tritsch.org
description: >
  Welcome to the Home of Innolocity (the velocity of innovation)
  and the Home of The Extreme Digital Nomad (tedn).
baseurl: ""
url: "http://www.tritsch.org"
twitter_username: innolocity
github_username: rolandtritsch

# Build settings
markdown: kramdown

plugins:
  - jekyll-archives

jekyll-archives:
  enabled: all
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
